### ISSUE TITLE
Cannot change the value of a parameter within buildmodel

### ISSUE THREAD

**Issue by kupiqu** [jsherfey/dnsim#6]
I can modify a parameter value within the paramters field, e.g. defined value for g_m in the mechanism is 1.2 and can change it to 0.8 by:

g_m = 0.8;
MSNpop_spec.nodes(1).parameters = {'g_m',g_m};

However, I cannot change it again later within the buildmodel, e.g.:

g_m =1.2;
models{1} = buildmodel(MSNpop_spec,'override', {'MSN','g_m',g_m},'verbose',1);

the verbose information about the model is telling that g_m is still 0.8, beyond that, no apparent error occurs or any info about the issue is reported.

**Comment by jsherfey** [comment]
The syntax used for overriding parameters using the current version of buildmodel() is incorrect. I think the current requirements are non-intuitive and should be changed so that the statement you entered would work (see below).
This should work now:
models{1} = buildmodel(MSNpop_spec,'override', {'MSN','parameters','g_m',g_m},'verbose',1);

This is confusing because overriding different model aspects currently requires using different synax.
- Override number of MSN cells: {'MSN','N',NumCells}
  where NumCells is the number of cells desired and 'N' is a built-in variable name
- Override MSN cell name: {'MSN','label','New_MSN_label'}
  where 'label' is a built-in variable name
- Override parameters: {'MSN','parameters','param',value} 
  where 'param' is the name of the parameter to change and value is the value you want it to have

I think this should be changed in the future. It may be possible to simply remove the need for specifying 'parameters' and to add checks in buildmodel() for 'label' and 'N' as special cases. After that, the statement above would work. 
All aspects to be overriden would then take this form:
{'Cell_or_Connection_Name', 'Thing_to_override', New_Value}

Other ideas?

I will test that this week and make sure it's a viable option. I would also add a check for the inclusion of 'parameters' to provide backwards compatibility if we decide to go with that approach.

**Comment by kupiqu** [comment]
Ok, I got it wrong when we talked about that then.

What you say about this transparent way of introducing changes without worrying if they are about parameters, labels or number of cells, sounds great to me. Feel free to close the issue as it is solved, or keep it open for diiscussion about these changes that you proposed... 

There is another concern that I have that is rather general so I'll submit another issue for  that.
